// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ModelkitModelsColumns holds the columns for the "modelkit_models" table.
	ModelkitModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID, Nullable: true},
		{Name: "model_name", Type: field.TypeString},
		{Name: "model_type", Type: field.TypeString},
		{Name: "show_name", Type: field.TypeString, Nullable: true},
		{Name: "api_base", Type: field.TypeString},
		{Name: "api_key", Type: field.TypeString},
		{Name: "api_version", Type: field.TypeString, Nullable: true},
		{Name: "api_header", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "is_internal", Type: field.TypeBool, Default: false},
		{Name: "provider", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "context_length", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ModelkitModelsTable holds the schema information for the "modelkit_models" table.
	ModelkitModelsTable = &schema.Table{
		Name:       "modelkit_models",
		Columns:    ModelkitModelsColumns,
		PrimaryKey: []*schema.Column{ModelkitModelsColumns[0]},
	}
	// ModelkitModelProvidersColumns holds the columns for the "modelkit_model_providers" table.
	ModelkitModelProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "api_base", Type: field.TypeString},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ModelkitModelProvidersTable holds the schema information for the "modelkit_model_providers" table.
	ModelkitModelProvidersTable = &schema.Table{
		Name:       "modelkit_model_providers",
		Columns:    ModelkitModelProvidersColumns,
		PrimaryKey: []*schema.Column{ModelkitModelProvidersColumns[0]},
	}
	// ModelkitModelProviderModelsColumns holds the columns for the "modelkit_model_provider_models" table.
	ModelkitModelProviderModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "provider_id", Type: field.TypeString, Nullable: true},
	}
	// ModelkitModelProviderModelsTable holds the schema information for the "modelkit_model_provider_models" table.
	ModelkitModelProviderModelsTable = &schema.Table{
		Name:       "modelkit_model_provider_models",
		Columns:    ModelkitModelProviderModelsColumns,
		PrimaryKey: []*schema.Column{ModelkitModelProviderModelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "modelkit_model_provider_models_modelkit_model_providers_models",
				Columns:    []*schema.Column{ModelkitModelProviderModelsColumns[4]},
				RefColumns: []*schema.Column{ModelkitModelProvidersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ModelkitModelsTable,
		ModelkitModelProvidersTable,
		ModelkitModelProviderModelsTable,
	}
)

func init() {
	ModelkitModelsTable.Annotation = &entsql.Annotation{
		Table: "modelkit_models",
	}
	ModelkitModelProvidersTable.Annotation = &entsql.Annotation{
		Table: "modelkit_model_providers",
	}
	ModelkitModelProviderModelsTable.ForeignKeys[0].RefTable = ModelkitModelProvidersTable
	ModelkitModelProviderModelsTable.Annotation = &entsql.Annotation{
		Table: "modelkit_model_provider_models",
	}
}
