// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chaitin/ModelKit/backend/db/modelapiconfig"
	"github.com/chaitin/ModelKit/backend/db/predicate"
)

// ModelAPIConfigDelete is the builder for deleting a ModelAPIConfig entity.
type ModelAPIConfigDelete struct {
	config
	hooks    []Hook
	mutation *ModelAPIConfigMutation
}

// Where appends a list predicates to the ModelAPIConfigDelete builder.
func (macd *ModelAPIConfigDelete) Where(ps ...predicate.ModelAPIConfig) *ModelAPIConfigDelete {
	macd.mutation.Where(ps...)
	return macd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (macd *ModelAPIConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, macd.sqlExec, macd.mutation, macd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (macd *ModelAPIConfigDelete) ExecX(ctx context.Context) int {
	n, err := macd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (macd *ModelAPIConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(modelapiconfig.Table, sqlgraph.NewFieldSpec(modelapiconfig.FieldID, field.TypeUUID))
	if ps := macd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, macd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	macd.mutation.done = true
	return affected, err
}

// ModelAPIConfigDeleteOne is the builder for deleting a single ModelAPIConfig entity.
type ModelAPIConfigDeleteOne struct {
	macd *ModelAPIConfigDelete
}

// Where appends a list predicates to the ModelAPIConfigDelete builder.
func (macdo *ModelAPIConfigDeleteOne) Where(ps ...predicate.ModelAPIConfig) *ModelAPIConfigDeleteOne {
	macdo.macd.mutation.Where(ps...)
	return macdo
}

// Exec executes the deletion query.
func (macdo *ModelAPIConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := macdo.macd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{modelapiconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (macdo *ModelAPIConfigDeleteOne) ExecX(ctx context.Context) {
	if err := macdo.Exec(ctx); err != nil {
		panic(err)
	}
}
