// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chaitin/ModelKit/backend/db/model"
	"github.com/chaitin/ModelKit/backend/db/modelapiconfig"
	"github.com/chaitin/ModelKit/backend/db/predicate"
	"github.com/google/uuid"
)

// ModelAPIConfigQuery is the builder for querying ModelAPIConfig entities.
type ModelAPIConfigQuery struct {
	config
	ctx        *QueryContext
	order      []modelapiconfig.OrderOption
	inters     []Interceptor
	predicates []predicate.ModelAPIConfig
	withModel  *ModelQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ModelAPIConfigQuery builder.
func (macq *ModelAPIConfigQuery) Where(ps ...predicate.ModelAPIConfig) *ModelAPIConfigQuery {
	macq.predicates = append(macq.predicates, ps...)
	return macq
}

// Limit the number of records to be returned by this query.
func (macq *ModelAPIConfigQuery) Limit(limit int) *ModelAPIConfigQuery {
	macq.ctx.Limit = &limit
	return macq
}

// Offset to start from.
func (macq *ModelAPIConfigQuery) Offset(offset int) *ModelAPIConfigQuery {
	macq.ctx.Offset = &offset
	return macq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (macq *ModelAPIConfigQuery) Unique(unique bool) *ModelAPIConfigQuery {
	macq.ctx.Unique = &unique
	return macq
}

// Order specifies how the records should be ordered.
func (macq *ModelAPIConfigQuery) Order(o ...modelapiconfig.OrderOption) *ModelAPIConfigQuery {
	macq.order = append(macq.order, o...)
	return macq
}

// QueryModel chains the current query on the "model" edge.
func (macq *ModelAPIConfigQuery) QueryModel() *ModelQuery {
	query := (&ModelClient{config: macq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := macq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := macq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(modelapiconfig.Table, modelapiconfig.FieldID, selector),
			sqlgraph.To(model.Table, model.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, modelapiconfig.ModelTable, modelapiconfig.ModelColumn),
		)
		fromU = sqlgraph.SetNeighbors(macq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ModelAPIConfig entity from the query.
// Returns a *NotFoundError when no ModelAPIConfig was found.
func (macq *ModelAPIConfigQuery) First(ctx context.Context) (*ModelAPIConfig, error) {
	nodes, err := macq.Limit(1).All(setContextOp(ctx, macq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{modelapiconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (macq *ModelAPIConfigQuery) FirstX(ctx context.Context) *ModelAPIConfig {
	node, err := macq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ModelAPIConfig ID from the query.
// Returns a *NotFoundError when no ModelAPIConfig ID was found.
func (macq *ModelAPIConfigQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = macq.Limit(1).IDs(setContextOp(ctx, macq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{modelapiconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (macq *ModelAPIConfigQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := macq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ModelAPIConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ModelAPIConfig entity is found.
// Returns a *NotFoundError when no ModelAPIConfig entities are found.
func (macq *ModelAPIConfigQuery) Only(ctx context.Context) (*ModelAPIConfig, error) {
	nodes, err := macq.Limit(2).All(setContextOp(ctx, macq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{modelapiconfig.Label}
	default:
		return nil, &NotSingularError{modelapiconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (macq *ModelAPIConfigQuery) OnlyX(ctx context.Context) *ModelAPIConfig {
	node, err := macq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ModelAPIConfig ID in the query.
// Returns a *NotSingularError when more than one ModelAPIConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (macq *ModelAPIConfigQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = macq.Limit(2).IDs(setContextOp(ctx, macq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{modelapiconfig.Label}
	default:
		err = &NotSingularError{modelapiconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (macq *ModelAPIConfigQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := macq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ModelAPIConfigs.
func (macq *ModelAPIConfigQuery) All(ctx context.Context) ([]*ModelAPIConfig, error) {
	ctx = setContextOp(ctx, macq.ctx, ent.OpQueryAll)
	if err := macq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ModelAPIConfig, *ModelAPIConfigQuery]()
	return withInterceptors[[]*ModelAPIConfig](ctx, macq, qr, macq.inters)
}

// AllX is like All, but panics if an error occurs.
func (macq *ModelAPIConfigQuery) AllX(ctx context.Context) []*ModelAPIConfig {
	nodes, err := macq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ModelAPIConfig IDs.
func (macq *ModelAPIConfigQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if macq.ctx.Unique == nil && macq.path != nil {
		macq.Unique(true)
	}
	ctx = setContextOp(ctx, macq.ctx, ent.OpQueryIDs)
	if err = macq.Select(modelapiconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (macq *ModelAPIConfigQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := macq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (macq *ModelAPIConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, macq.ctx, ent.OpQueryCount)
	if err := macq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, macq, querierCount[*ModelAPIConfigQuery](), macq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (macq *ModelAPIConfigQuery) CountX(ctx context.Context) int {
	count, err := macq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (macq *ModelAPIConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, macq.ctx, ent.OpQueryExist)
	switch _, err := macq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (macq *ModelAPIConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := macq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ModelAPIConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (macq *ModelAPIConfigQuery) Clone() *ModelAPIConfigQuery {
	if macq == nil {
		return nil
	}
	return &ModelAPIConfigQuery{
		config:     macq.config,
		ctx:        macq.ctx.Clone(),
		order:      append([]modelapiconfig.OrderOption{}, macq.order...),
		inters:     append([]Interceptor{}, macq.inters...),
		predicates: append([]predicate.ModelAPIConfig{}, macq.predicates...),
		withModel:  macq.withModel.Clone(),
		// clone intermediate query.
		sql:       macq.sql.Clone(),
		path:      macq.path,
		modifiers: append([]func(*sql.Selector){}, macq.modifiers...),
	}
}

// WithModel tells the query-builder to eager-load the nodes that are connected to
// the "model" edge. The optional arguments are used to configure the query builder of the edge.
func (macq *ModelAPIConfigQuery) WithModel(opts ...func(*ModelQuery)) *ModelAPIConfigQuery {
	query := (&ModelClient{config: macq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	macq.withModel = query
	return macq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ModelID uuid.UUID `json:"model_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ModelAPIConfig.Query().
//		GroupBy(modelapiconfig.FieldModelID).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (macq *ModelAPIConfigQuery) GroupBy(field string, fields ...string) *ModelAPIConfigGroupBy {
	macq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ModelAPIConfigGroupBy{build: macq}
	grbuild.flds = &macq.ctx.Fields
	grbuild.label = modelapiconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ModelID uuid.UUID `json:"model_id,omitempty"`
//	}
//
//	client.ModelAPIConfig.Query().
//		Select(modelapiconfig.FieldModelID).
//		Scan(ctx, &v)
func (macq *ModelAPIConfigQuery) Select(fields ...string) *ModelAPIConfigSelect {
	macq.ctx.Fields = append(macq.ctx.Fields, fields...)
	sbuild := &ModelAPIConfigSelect{ModelAPIConfigQuery: macq}
	sbuild.label = modelapiconfig.Label
	sbuild.flds, sbuild.scan = &macq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ModelAPIConfigSelect configured with the given aggregations.
func (macq *ModelAPIConfigQuery) Aggregate(fns ...AggregateFunc) *ModelAPIConfigSelect {
	return macq.Select().Aggregate(fns...)
}

func (macq *ModelAPIConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range macq.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, macq); err != nil {
				return err
			}
		}
	}
	for _, f := range macq.ctx.Fields {
		if !modelapiconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if macq.path != nil {
		prev, err := macq.path(ctx)
		if err != nil {
			return err
		}
		macq.sql = prev
	}
	return nil
}

func (macq *ModelAPIConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ModelAPIConfig, error) {
	var (
		nodes       = []*ModelAPIConfig{}
		_spec       = macq.querySpec()
		loadedTypes = [1]bool{
			macq.withModel != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ModelAPIConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ModelAPIConfig{config: macq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(macq.modifiers) > 0 {
		_spec.Modifiers = macq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, macq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := macq.withModel; query != nil {
		if err := macq.loadModel(ctx, query, nodes, nil,
			func(n *ModelAPIConfig, e *Model) { n.Edges.Model = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (macq *ModelAPIConfigQuery) loadModel(ctx context.Context, query *ModelQuery, nodes []*ModelAPIConfig, init func(*ModelAPIConfig), assign func(*ModelAPIConfig, *Model)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ModelAPIConfig)
	for i := range nodes {
		fk := nodes[i].ModelID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(model.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "model_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (macq *ModelAPIConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := macq.querySpec()
	if len(macq.modifiers) > 0 {
		_spec.Modifiers = macq.modifiers
	}
	_spec.Node.Columns = macq.ctx.Fields
	if len(macq.ctx.Fields) > 0 {
		_spec.Unique = macq.ctx.Unique != nil && *macq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, macq.driver, _spec)
}

func (macq *ModelAPIConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(modelapiconfig.Table, modelapiconfig.Columns, sqlgraph.NewFieldSpec(modelapiconfig.FieldID, field.TypeUUID))
	_spec.From = macq.sql
	if unique := macq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if macq.path != nil {
		_spec.Unique = true
	}
	if fields := macq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelapiconfig.FieldID)
		for i := range fields {
			if fields[i] != modelapiconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if macq.withModel != nil {
			_spec.Node.AddColumnOnce(modelapiconfig.FieldModelID)
		}
	}
	if ps := macq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := macq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := macq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := macq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (macq *ModelAPIConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(macq.driver.Dialect())
	t1 := builder.Table(modelapiconfig.Table)
	columns := macq.ctx.Fields
	if len(columns) == 0 {
		columns = modelapiconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if macq.sql != nil {
		selector = macq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if macq.ctx.Unique != nil && *macq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range macq.modifiers {
		m(selector)
	}
	for _, p := range macq.predicates {
		p(selector)
	}
	for _, p := range macq.order {
		p(selector)
	}
	if offset := macq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := macq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (macq *ModelAPIConfigQuery) ForUpdate(opts ...sql.LockOption) *ModelAPIConfigQuery {
	if macq.driver.Dialect() == dialect.Postgres {
		macq.Unique(false)
	}
	macq.modifiers = append(macq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return macq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (macq *ModelAPIConfigQuery) ForShare(opts ...sql.LockOption) *ModelAPIConfigQuery {
	if macq.driver.Dialect() == dialect.Postgres {
		macq.Unique(false)
	}
	macq.modifiers = append(macq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return macq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (macq *ModelAPIConfigQuery) Modify(modifiers ...func(s *sql.Selector)) *ModelAPIConfigSelect {
	macq.modifiers = append(macq.modifiers, modifiers...)
	return macq.Select()
}

// ModelAPIConfigGroupBy is the group-by builder for ModelAPIConfig entities.
type ModelAPIConfigGroupBy struct {
	selector
	build *ModelAPIConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (macgb *ModelAPIConfigGroupBy) Aggregate(fns ...AggregateFunc) *ModelAPIConfigGroupBy {
	macgb.fns = append(macgb.fns, fns...)
	return macgb
}

// Scan applies the selector query and scans the result into the given value.
func (macgb *ModelAPIConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, macgb.build.ctx, ent.OpQueryGroupBy)
	if err := macgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModelAPIConfigQuery, *ModelAPIConfigGroupBy](ctx, macgb.build, macgb, macgb.build.inters, v)
}

func (macgb *ModelAPIConfigGroupBy) sqlScan(ctx context.Context, root *ModelAPIConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(macgb.fns))
	for _, fn := range macgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*macgb.flds)+len(macgb.fns))
		for _, f := range *macgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*macgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := macgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ModelAPIConfigSelect is the builder for selecting fields of ModelAPIConfig entities.
type ModelAPIConfigSelect struct {
	*ModelAPIConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (macs *ModelAPIConfigSelect) Aggregate(fns ...AggregateFunc) *ModelAPIConfigSelect {
	macs.fns = append(macs.fns, fns...)
	return macs
}

// Scan applies the selector query and scans the result into the given value.
func (macs *ModelAPIConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, macs.ctx, ent.OpQuerySelect)
	if err := macs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModelAPIConfigQuery, *ModelAPIConfigSelect](ctx, macs.ModelAPIConfigQuery, macs, macs.inters, v)
}

func (macs *ModelAPIConfigSelect) sqlScan(ctx context.Context, root *ModelAPIConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(macs.fns))
	for _, fn := range macs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*macs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := macs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (macs *ModelAPIConfigSelect) Modify(modifiers ...func(s *sql.Selector)) *ModelAPIConfigSelect {
	macs.modifiers = append(macs.modifiers, modifiers...)
	return macs
}
