// Code generated by ent, DO NOT EDIT.

package db

import "context"

// PageInfo 分页信息
type PageInfo struct {
	NextToken   string `json:"next_token,omitempty"`
	HasNextPage bool   `json:"has_next_page"`
	TotalCount  int64  `json:"total_count"`
}

func (m *ModelQuery) Page(ctx context.Context, page, size int) ([]*Model, *PageInfo, error) {
	cnt, err := m.Count(ctx)
	if err != nil {
		return nil, nil, err
	}
	offset := size * (page - 1)
	rs, err := m.Offset(offset).Limit(size).All(ctx)
	if err != nil {
		return nil, nil, err
	}
	has := (page * size) < cnt
	return rs, &PageInfo{HasNextPage: has, TotalCount: int64(cnt)}, nil
}
