// Code generated by ent, DO NOT EDIT.

package db

import (
	"time"

	"github.com/chaitin/ModelKit/backend/consts"
	"github.com/chaitin/ModelKit/backend/db/model"
	"github.com/chaitin/ModelKit/backend/db/modelprovider"
	"github.com/chaitin/ModelKit/backend/db/modelprovidermodel"
	"github.com/chaitin/ModelKit/backend/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	modelFields := schema.Model{}.Fields()
	_ = modelFields
	// modelDescIsInternal is the schema descriptor for is_internal field.
	modelDescIsInternal := modelFields[10].Descriptor()
	// model.DefaultIsInternal holds the default value on creation for the is_internal field.
	model.DefaultIsInternal = modelDescIsInternal.Default.(bool)
	// modelDescStatus is the schema descriptor for status field.
	modelDescStatus := modelFields[12].Descriptor()
	// model.DefaultStatus holds the default value on creation for the status field.
	model.DefaultStatus = consts.ModelStatus(modelDescStatus.Default.(string))
	// modelDescCreatedAt is the schema descriptor for created_at field.
	modelDescCreatedAt := modelFields[15].Descriptor()
	// model.DefaultCreatedAt holds the default value on creation for the created_at field.
	model.DefaultCreatedAt = modelDescCreatedAt.Default.(func() time.Time)
	// modelDescUpdatedAt is the schema descriptor for updated_at field.
	modelDescUpdatedAt := modelFields[16].Descriptor()
	// model.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	model.DefaultUpdatedAt = modelDescUpdatedAt.Default.(func() time.Time)
	// model.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	model.UpdateDefaultUpdatedAt = modelDescUpdatedAt.UpdateDefault.(func() time.Time)
	modelproviderFields := schema.ModelProvider{}.Fields()
	_ = modelproviderFields
	// modelproviderDescName is the schema descriptor for name field.
	modelproviderDescName := modelproviderFields[1].Descriptor()
	// modelprovider.NameValidator is a validator for the "name" field. It is called by the builders before save.
	modelprovider.NameValidator = modelproviderDescName.Validators[0].(func(string) error)
	// modelproviderDescAPIBase is the schema descriptor for api_base field.
	modelproviderDescAPIBase := modelproviderFields[2].Descriptor()
	// modelprovider.APIBaseValidator is a validator for the "api_base" field. It is called by the builders before save.
	modelprovider.APIBaseValidator = modelproviderDescAPIBase.Validators[0].(func(string) error)
	// modelproviderDescPriority is the schema descriptor for priority field.
	modelproviderDescPriority := modelproviderFields[3].Descriptor()
	// modelprovider.DefaultPriority holds the default value on creation for the priority field.
	modelprovider.DefaultPriority = modelproviderDescPriority.Default.(int)
	// modelproviderDescCreatedAt is the schema descriptor for created_at field.
	modelproviderDescCreatedAt := modelproviderFields[4].Descriptor()
	// modelprovider.DefaultCreatedAt holds the default value on creation for the created_at field.
	modelprovider.DefaultCreatedAt = modelproviderDescCreatedAt.Default.(func() time.Time)
	// modelproviderDescUpdatedAt is the schema descriptor for updated_at field.
	modelproviderDescUpdatedAt := modelproviderFields[5].Descriptor()
	// modelprovider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	modelprovider.DefaultUpdatedAt = modelproviderDescUpdatedAt.Default.(func() time.Time)
	// modelprovider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	modelprovider.UpdateDefaultUpdatedAt = modelproviderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// modelproviderDescID is the schema descriptor for id field.
	modelproviderDescID := modelproviderFields[0].Descriptor()
	// modelprovider.IDValidator is a validator for the "id" field. It is called by the builders before save.
	modelprovider.IDValidator = modelproviderDescID.Validators[0].(func(string) error)
	modelprovidermodelFields := schema.ModelProviderModel{}.Fields()
	_ = modelprovidermodelFields
	// modelprovidermodelDescName is the schema descriptor for name field.
	modelprovidermodelDescName := modelprovidermodelFields[1].Descriptor()
	// modelprovidermodel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	modelprovidermodel.NameValidator = modelprovidermodelDescName.Validators[0].(func(string) error)
	// modelprovidermodelDescCreatedAt is the schema descriptor for created_at field.
	modelprovidermodelDescCreatedAt := modelprovidermodelFields[3].Descriptor()
	// modelprovidermodel.DefaultCreatedAt holds the default value on creation for the created_at field.
	modelprovidermodel.DefaultCreatedAt = modelprovidermodelDescCreatedAt.Default.(func() time.Time)
	// modelprovidermodelDescUpdatedAt is the schema descriptor for updated_at field.
	modelprovidermodelDescUpdatedAt := modelprovidermodelFields[4].Descriptor()
	// modelprovidermodel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	modelprovidermodel.DefaultUpdatedAt = modelprovidermodelDescUpdatedAt.Default.(func() time.Time)
	// modelprovidermodel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	modelprovidermodel.UpdateDefaultUpdatedAt = modelprovidermodelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// modelprovidermodelDescID is the schema descriptor for id field.
	modelprovidermodelDescID := modelprovidermodelFields[0].Descriptor()
	// modelprovidermodel.DefaultID holds the default value on creation for the id field.
	modelprovidermodel.DefaultID = modelprovidermodelDescID.Default.(func() uuid.UUID)
}
