import { ModelProviderMap } from '../types/types';

// 默认模型提供商配置
export const DEFAULT_MODEL_PROVIDERS: ModelProviderMap = {
  BaiZhiCloud: {
    label: 'BaiZhiCloud',
    cn: '百智云',
    icon: 'ikun-baizhiyunlogo',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: true,
    rerank: true,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://model-square.app.baizhi.cloud/token',
    defaultBaseUrl: 'https://model-square.app.baizhi.cloud/v1',
  },
  ZhiPu: {
    label: 'ZhiPu',
    cn: '智谱',
    icon: 'ikun-zhipuqingyan', // 需要添加对应的图标
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://bigmodel.cn/usercenter/proj-mgmt/apikeys',
    defaultBaseUrl: 'https://open.bigmodel.cn/api/paas/v4',
  },
  DeepSeek: {
    label: 'DeepSeek',
    cn: 'DeepSeek',
    icon: 'ikun-deepseek',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://platform.deepseek.com/api_keys',
    defaultBaseUrl: 'https://api.deepseek.com/v1',
  },
  Hunyuan: {
    label: 'Hunyuan',
    cn: '腾讯混元',
    icon: 'ikun-tengxunhunyuan',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://console.cloud.tencent.com/hunyuan/api-key',
    defaultBaseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
  },
  BaiLian: {
    label: 'BaiLian',
    cn: '阿里云百炼',
    icon: 'ikun-aliyunbailian',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: true,
    rerank: true,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://bailian.console.aliyun.com/?tab=model#/api-key',
    defaultBaseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
  },
  Volcengine: {
    label: 'Volcengine',
    cn: '火山引擎',
    icon: 'ikun-huoshanyinqing',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
  },
  OpenAI: {
    label: 'OpenAI',
    cn: 'OpenAI',
    icon: 'ikun-chatgpt-copy',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://platform.openai.com/api-keys',
    defaultBaseUrl: 'https://api.openai.com/v1',
  },
  Ollama: {
    label: 'Ollama',
    cn: 'Ollama',
    icon: 'ikun-ollama',
    urlWrite: true,
    secretRequired: false,
    customHeader: true,
    chat: true,
    code: true,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://github.com/ollama/ollama/tree/main/docs',
    addingModelTutorial: 'https://github.com/chaitin/ModelKit/blob/main/docs/AddinModelTutorial.md',
    defaultBaseUrl: 'http://172.17.0.1:11434',
  },
  SiliconFlow: {
    label: 'SiliconFlow',
    cn: '硅基流动',
    icon: 'ikun-siliconflow1',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://cloud.siliconflow.cn/me/account/ak',
    defaultBaseUrl: 'https://api.siliconflow.cn/v1',
  },
  Moonshot: {
    label: 'Moonshot',
    cn: '月之暗面',
    icon: 'ikun-Kim',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://platform.moonshot.cn/console/api-keys',
    defaultBaseUrl: 'https://api.moonshot.cn/v1',
  },
  AzureOpenAI: {
    label: 'AzureOpenAI',
    cn: 'Azure OpenAI',
    icon: 'ikun-azure',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://portal.azure.com/#view/Microsoft_Azure_ProjectOxford/CognitiveServicesHub/~/OpenAI',
    defaultBaseUrl: 'https://<resource_name>.openai.azure.com',
  },
  Gemini: {
    label: 'Gemini',
    cn: 'Gemini',
    icon: 'ikun-gemini',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://aistudio.google.com/app/apikey',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com',
  },
  Qiniu: {
    label: 'Qiniu',
    cn: '七牛云',
    icon: 'ikun-qiniuyun',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: false,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://portal.qiniu.com/ai-inference/api-key',
    defaultBaseUrl: 'https://api.qnaigc.com/v1',
  },
  // NewAPI: {
  //   label: 'NewAPI',
  //   cn: 'New API',
  //   icon: 'ikun-newapi',
  //   urlWrite: true,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: '',
  //   defaultBaseUrl: 'http://localhost:3000/v1',
  // },
  // LMStudio: {
  //   label: 'LMStudio',
  //   cn: 'LM Studio',
  //   icon: 'ikun-lmstudio',
  //   urlWrite: true,
  //   secretRequired: false,
  //   customHeader: false,
  //   modelDocumentUrl: '',
  //   defaultBaseUrl: 'http://localhost:1234/v1',
  // },
  // Anthropic: {
  //   label: 'Anthropic',
  //   cn: 'Anthropic',
  //   icon: 'ikun-anthropic',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://console.anthropic.com/account/keys',
  //   defaultBaseUrl: 'https://api.anthropic.com',
  // },
  // GitHub: {
  //   label: 'GitHub',
  //   cn: 'GitHub Models',
  //   icon: 'ikun-github',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://github.com/settings/tokens',
  //   defaultBaseUrl: 'https://models.github.ai/catalog',
  // },
  Xinference: {
    label: 'Xinference',
    cn: 'Xinference',
    icon: 'ikun-Xinference',
    urlWrite: true,
    secretRequired: false,
    customHeader: false,
    chat: true,
    code: true,
    embedding: true,
    rerank: true,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://inference.readthedocs.io/zh-cn/v1.2.0/getting_started/installation.html#installation',
    addingModelTutorial: 'https://github.com/chaitin/ModelKit/blob/main/docs/AddinModelTutorial.md',
    defaultBaseUrl: 'http://172.17.0.1:9997',
  },
  gpustack: {
    label: 'gpustack',
    cn: 'GPUStack',
    icon: 'ikun-gpustack',
    urlWrite: true,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: true,
    rerank: true,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://docs.gpustack.ai/latest/quickstart/',
    addingModelTutorial: 'https://github.com/chaitin/ModelKit/blob/main/docs/AddinModelTutorial.md',
    defaultBaseUrl: 'http://172.17.0.1',
  },
  Yi: {
    label: 'Yi',
    cn: '零一万物',
    icon: 'ikun-lingyiwanwu',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: false,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://platform.lingyiwanwu.com/apikeys',
    defaultBaseUrl: 'https://api.lingyiwanwu.com/v1',
  },
  // Baichuan: {
  //   label: 'Baichuan',
  //   cn: '百川智能',
  //   icon: 'ikun-baichuan',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://platform.baichuan-ai.com/console/apikey',
  //   defaultBaseUrl: 'https://api.baichuan-ai.com/v1',
  // },
  // Ph8: {
  //   label: 'Ph8',
  //   cn: 'PH8大模型开放平台',
  //   icon: 'ikun-ph8',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: '',
  //   defaultBaseUrl: 'https://ph8.co/v1',
  // },
  // MiniMax: {
  //   label: 'MiniMax',
  //   cn: 'MiniMax',
  //   icon: 'ikun-minimax',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://api.minimax.chat/user-center/basic-information/interface-key',
  //   defaultBaseUrl: 'https://api.minimaxi.com/v1',
  // },
  // Groq: {
  //   label: 'Groq',
  //   cn: 'Groq',
  //   icon: 'ikun-groq',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://console.groq.com/keys',
  //   defaultBaseUrl: 'https://api.groq.com/openai/v1',
  // },
  // Together: {
  //   label: 'Together',
  //   cn: 'Together',
  //   icon: 'ikun-together',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://api.together.xyz/settings/api-keys',
  //   defaultBaseUrl: 'https://api.together.xyz/v1',
  // },
  // Jina: {
  //   label: 'Jina',
  //   cn: 'Jina',
  //   icon: 'ikun-hyperbolic',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: '',
  //   defaultBaseUrl: 'https://api.jina.ai/v1',
  // },

  CTYun: {
    label: 'CTYun',
    cn: '天翼云息壤',
    icon: 'ikun-tianyiyun',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: false,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://huiju.ctyun.cn/service/serviceGroup',
    defaultBaseUrl: 'https://wishub-x1.ctyun.cn/v1',
  },
  TencentTI: {
    label: 'TencentTI',
    cn: '腾讯云TI',
    icon: 'ikun-tengxunyun',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: false,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://console.cloud.tencent.com/lkeap/api',
    defaultBaseUrl: 'https://api.lkeap.cloud.tencent.com/v1',
  },
  BaiDuQianFan: {
    label: 'BaiDuQianFan',
    cn: '百度云千帆',
    icon: 'ikun-baiduyun',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: false,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://console.bce.baidu.com/iam/#/iam/apikey/list',
    defaultBaseUrl: 'https://qianfan.baidubce.com/v2',
  },
  ModelScope: {
    label: 'ModelScope',
    cn: '魔搭社区',
    icon: 'ikun-modaGPT',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: false,
    code: false,
    embedding: false,
    rerank: false,
    analysis: false,
    analysis_vl: false,
    modelDocumentUrl: 'https://modelscope.cn/my/myaccesstoken',
    defaultBaseUrl: 'https://api-inference.modelscope.cn/v1',
  },
  Infini: {
    label: 'Infini',
    cn: '无问芯穹',
    icon: 'ikun-infini',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://cloud.infini-ai.com/iam/secret/key',
    defaultBaseUrl: 'https://cloud.infini-ai.com/maas/v1',
  },
  StepFun: {
    label: 'StepFun',
    cn: '阶跃星辰',
    icon: 'ikun-step',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: false,
    code: false,
    embedding: false,
    rerank: false,
    analysis: false,
    analysis_vl: false,
    modelDocumentUrl: 'https://platform.stepfun.com/interface-key',
    defaultBaseUrl: 'https://api.stepfun.com/v1',
  },
  LanYun: {
    label: 'LanYun',
    cn: '蓝耘科技',
    icon: 'ikun-lanyun',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: false,
    code: false,
    embedding: false,
    rerank: false,
    analysis: false,
    analysis_vl: false,
    modelDocumentUrl: 'https://maas.lanyun.net/#/system/apiKey',
    defaultBaseUrl: 'https://maas-api.lanyun.net/v1',
  },
  AlayaNew: {
    label: 'AlayaNew',
    cn: '九章智算云',
    icon: 'ikun-alayanew',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: false,
    code: false,
    embedding: false,
    rerank: false,
    analysis: false,
    analysis_vl: false,
    modelDocumentUrl: ' https://www.alayanew.com/backend/register',
    defaultBaseUrl: 'https://deepseek.alayanew.com/v1',
  },
  PPIO: {
    label: 'PPIO',
    cn: '欧派云',
    icon: 'ikun-ppio',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: false,
    code: true,
    embedding: false,
    rerank: false,
    analysis: false,
    analysis_vl: false,
    modelDocumentUrl: 'https://ppio.com/settings/key-management',
    defaultBaseUrl: 'https://api.ppinfra.com/v3/openai',
  },
  AiHubMix: {
    label: 'AiHubMix',
    cn: 'AiHubMix',
    icon: 'ikun-aihubmix',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: false,
    code: false,
    embedding: false,
    rerank: false,
    analysis: false,
    analysis_vl: false,
    modelDocumentUrl: 'https://aihubmix.com',
    defaultBaseUrl: 'https://aihubmix.com/v1',
  },
  OcoolAI: {
    label: 'OcoolAI',
    cn: 'OcoolAI',
    icon: 'ikun-ocoolai',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://one.ocoolai.com/token',
    defaultBaseUrl: 'https://api.ocoolai.com/v1',
  },
  DMXAPI: {
    label: 'DMXAPI',
    cn: 'DMXAPI',
    icon: 'ikun-DMXAPI',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: false,
    code: false,
    embedding: false,
    rerank: false,
    analysis: false,
    analysis_vl: false,
    modelDocumentUrl: 'https://www.dmxapi.cn/register',
    defaultBaseUrl: 'https://www.dmxapi.cn/v1',
  },
  BurnCloud: {
    label: 'BurnCloud',
    cn: 'BurnCloud',
    icon: 'ikun-burncloud',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: false,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://ai.burncloud.com/console/token',
    defaultBaseUrl: 'https://ai.burncloud.com/v1',
  },
  // Grok: {
  //   label: 'Grok',
  //   cn: 'Grok',
  //   icon: 'ikun-grok',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://docs.x.ai/',
  //   defaultBaseUrl: 'https://api.x.ai/v1',
  // },
  Nvidia: {
    label: 'Nvidia',
    cn: '英伟达',
    icon: 'ikun-yingweida',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: false,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://build.nvidia.com/?integrate_nim=true&hosted_api=true&modal=integrate-nim',
    defaultBaseUrl: 'https://integrate.api.nvidia.com/v1',
  },
  TokenFlux: {
    label: 'TokenFlux',
    cn: 'TokenFlux',
    icon: 'ikun-tokenflux',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: false,
    code: false,
    embedding: false,
    rerank: false,
    analysis: false,
    analysis_vl: false,
    modelDocumentUrl: 'https://tokenflux.ai/docs',
    defaultBaseUrl: 'https://tokenflux.ai/v1',
  },
  AI302: {
    label: 'AI302',
    cn: '302.AI',
    icon: 'ikun-a-302ai',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://dash.302.ai/apis/list',
    defaultBaseUrl: 'https://api.302.ai/v1',
  },
  Cephalon: {
    label: 'Cephalon',
    cn: 'Cephalon',
    icon: 'ikun-cephalon',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: false,
    code: false,
    embedding: false,
    rerank: false,
    analysis: false,
    analysis_vl: false,
    modelDocumentUrl: 'https://cephalon.cloud/api',
    defaultBaseUrl: 'https://cephalon.cloud/user-center/v1/model',
  },
  OpenRouter: {
    label: 'OpenRouter',
    cn: 'OpenRouter',
    icon: 'ikun-openrouter',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: false,
    code: false,
    embedding: false,
    rerank: false,
    analysis: false,
    analysis_vl: false,
    modelDocumentUrl: 'https://openrouter.ai/settings/keys',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
  },
  Fireworks: {
    label: 'Fireworks',
    cn: 'Fireworks',
    icon: 'ikun-fireworks',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: true,
    code: true,
    embedding: false,
    rerank: false,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: 'https://app.fireworks.ai/settings/users/api-keys',
    defaultBaseUrl: 'https://api.fireworks.ai/inference/v1',
  },
  Mistral: {
    label: 'Mistral',
    cn: 'Mistral',
    icon: 'ikun-Mistral',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: false,
    code: false,
    embedding: false,
    rerank: false,
    analysis: false,
    analysis_vl: false,
    modelDocumentUrl: 'https://console.mistral.ai/api-keys/',
    defaultBaseUrl: 'https://api.mistral.ai/v1',
  },
  Perplexity: {
    label: 'Perplexity',
    cn: 'Perplexity',
    icon: 'ikun-perplexity',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: false,
    code: false,
    embedding: false,
    rerank: false,
    analysis: false,
    analysis_vl: false,
    modelDocumentUrl: 'https://www.perplexity.ai/settings/api',
    defaultBaseUrl: 'https://api.perplexity.ai',
  },
  Hyperbolic: {
    label: 'Hyperbolic',
    cn: 'Hyperbolic',
    icon: 'ikun-hyperbolic',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    chat: false,
    code: false,
    embedding: false,
    rerank: false,
    analysis: false,
    analysis_vl: false,
    modelDocumentUrl: 'https://app.hyperbolic.xyz/settings',
    defaultBaseUrl: 'https://api.hyperbolic.xyz/v1',
  },
  // VoyageAI: {
  //   label: 'VoyageAI',
  //   cn: 'Voyage AI',
  //   icon: 'ikun-voyageai',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: '',
  //   defaultBaseUrl: 'https://api.voyageai.com/v1',
  // },
  // Poe: {
  //   label: 'Poe',
  //   cn: 'Poe',
  //   icon: 'ikun-poe',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: '',
  //   defaultBaseUrl: 'https://api.poe.com/v1',
  // },
  Other: {
    label: 'Other',
    cn: '其他',
    icon: 'ikun-a-AIshezhi',
    urlWrite: true,
    secretRequired: false,
    customHeader: false,
    chat: true,
    code: true,
    embedding: true,
    rerank: true,
    analysis: true,
    analysis_vl: true,
    modelDocumentUrl: '',
    addingModelTutorial: 'https://github.com/chaitin/ModelKit/blob/main/docs/AddinModelTutorial.md',
    defaultBaseUrl: '',
  },
};
