import { ModelProviderMap } from '../types/types';

// 默认模型提供商配置
export const DEFAULT_MODEL_PROVIDERS: ModelProviderMap = {
  BaiZhiCloud: {
    label: 'BaiZhiCloud',
    cn: '百智云',
    icon: 'icon-baizhiyunlogo',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://model-square.app.baizhi.cloud/token',
    defaultBaseUrl: 'https://model-square.app.baizhi.cloud/v1',
  },
  ZhiPu: {
    label: 'ZhiPu',
    cn: '智谱',
    icon: 'icon-zhipuqingyan', // 需要添加对应的图标
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    defaultBaseUrl: 'https://open.bigmodel.cn/api/paas/v4',
  },
  DeepSeek: {
    label: 'DeepSeek',
    cn: 'DeepSeek',
    icon: 'icon-deepseek',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://platform.deepseek.com/api_keys',
    defaultBaseUrl: 'https://api.deepseek.com/v1',
  },
  Hunyuan: {
    label: 'Hunyuan',
    cn: '腾讯混元',
    icon: 'icon-tengxunhunyuan',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://console.cloud.tencent.com/hunyuan/start',
    defaultBaseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
  },
  BaiLian: {
    label: 'BaiLian',
    cn: '阿里云百炼',
    icon: 'icon-aliyunbailian',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://bailian.console.aliyun.com/?tab=model#/api-key',
    defaultBaseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
  },
  Volcengine: {
    label: 'Volcengine',
    cn: '火山引擎',
    icon: 'icon-huoshanyinqing',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
  },
  OpenAI: {
    label: 'OpenAI',
    cn: 'OpenAI',
    icon: 'icon-chatgpt',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://platform.openai.com/api-keys',
    defaultBaseUrl: 'https://api.openai.com/v1',
  },
  Ollama: {
    label: 'Ollama',
    cn: 'Ollama',
    icon: 'icon-ollama',
    urlWrite: true,
    secretRequired: false,
    customHeader: true,
    modelDocumentUrl: '',
    defaultBaseUrl: 'http://127.0.0.1:11434',
  },
  SiliconFlow: {
    label: 'SiliconFlow',
    cn: '硅基流动',
    icon: 'icon-a-ziyuan2',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://cloud.siliconflow.cn/account/ak',
    defaultBaseUrl: 'https://api.siliconflow.cn/v1',
  },
  Moonshot: {
    label: 'Moonshot',
    cn: '月之暗面',
    icon: 'icon-Kim',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://platform.moonshot.cn/console/api-keys',
    defaultBaseUrl: 'https://api.moonshot.cn/v1',
  },
  AzureOpenAI: {
    label: 'AzureOpenAI',
    cn: 'Azure OpenAI',
    icon: 'icon-azure',
    urlWrite: true,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://portal.azure.com/#view/Microsoft_Azure_ProjectOxford/CognitiveServicesHub/~/OpenAI',
    defaultBaseUrl: 'https://<resource_name>.openai.azure.com',
  },
  Gemini: {
    label: 'Gemini',
    cn: 'Gemini',
    icon: 'icon-gemini',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://ai.google.dev/gemini-api/docs',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com',
  },
  AiHubMix: {
    label: 'AiHubMix',
    cn: 'AiHubMix',
    icon: 'icon-aihubmix',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: '',
    defaultBaseUrl: 'https://aihubmix.com/v1',
  },
  OcoolAI: {
    label: 'OcoolAI',
    cn: 'OcoolAI',
    icon: 'icon-ocoolai',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: '',
    defaultBaseUrl: 'https://api.ocoolai.com/v1',
  },
  PPIO: {
    label: 'PPIO',
    cn: '欧派云',
    icon: 'icon-ppio',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: '',
    defaultBaseUrl: 'https://api.ppinfra.com/v3/openai',
  },
  AlayaNew: {
    label: 'AlayaNew',
    cn: '九章智算云',
    icon: 'icon-alayanew',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: '',
    defaultBaseUrl: 'https://deepseek.alayanew.com/v1',
  },
  Qiniu: {
    label: 'Qiniu',
    cn: '七牛云',
    icon: 'icon-qiniu',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: '',
    defaultBaseUrl: 'https://api.qnaigc.com/v1',
  },
  DMXAPI: {
    label: 'DMXAPI',
    cn: 'DMXAPI',
    icon: 'icon-dmxapi',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: '',
    defaultBaseUrl: 'https://www.dmxapi.cn/v1',
  },
  BurnCloud: {
    label: 'BurnCloud',
    cn: 'BurnCloud',
    icon: 'icon-burncloud',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: '',
    defaultBaseUrl: 'https://ai.burncloud.com/v1',
  },
  TokenFlux: {
    label: 'TokenFlux',
    cn: 'TokenFlux',
    icon: 'icon-tokenflux',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: '',
    defaultBaseUrl: 'https://tokenflux.ai/v1',
  },
  AI302: {
    label: 'AI302',
    cn: '302.AI',
    icon: 'icon-302ai',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: '',
    defaultBaseUrl: 'https://api.302.ai/v1',
  },
  Cephalon: {
    label: 'Cephalon',
    cn: 'Cephalon',
    icon: 'icon-cephalon',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: '',
    defaultBaseUrl: 'https://cephalon.cloud/user-center/v1/model',
  },
  LanYun: {
    label: 'LanYun',
    cn: '蓝耘科技',
    icon: 'icon-lanyun',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: '',
    defaultBaseUrl: 'https://maas-api.lanyun.net/v1',
  },
  OpenRouter: {
    label: 'OpenRouter',
    cn: 'OpenRouter',
    icon: 'icon-openrouter',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://openrouter.ai/keys',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
  },
  // NewAPI: {
  //   label: 'NewAPI',
  //   cn: 'New API',
  //   icon: 'icon-newapi',
  //   urlWrite: true,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: '',
  //   defaultBaseUrl: 'http://localhost:3000/v1',
  // },
  // LMStudio: {
  //   label: 'LMStudio',
  //   cn: 'LM Studio',
  //   icon: 'icon-lmstudio',
  //   urlWrite: true,
  //   secretRequired: false,
  //   customHeader: false,
  //   modelDocumentUrl: '',
  //   defaultBaseUrl: 'http://localhost:1234/v1',
  // },
  // Anthropic: {
  //   label: 'Anthropic',
  //   cn: 'Anthropic',
  //   icon: 'icon-anthropic',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://console.anthropic.com/account/keys',
  //   defaultBaseUrl: 'https://api.anthropic.com',
  // },
  GitHub: {
    label: 'GitHub',
    cn: 'GitHub Models',
    icon: 'icon-github',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://github.com/settings/tokens',
    defaultBaseUrl: 'https://models.github.ai/catalog',
  },
  Yi: {
    label: 'Yi',
    cn: '零一万物',
    icon: 'icon-yi',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://platform.lingyiwanwu.com/apikeys',
    defaultBaseUrl: 'https://api.lingyiwanwu.com/v1',
  },
  Baichuan: {
    label: 'Baichuan',
    cn: '百川智能',
    icon: 'icon-baichuan',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://platform.baichuan-ai.com/console/apikey',
    defaultBaseUrl: 'https://api.baichuan-ai.com/v1',
  },
  StepFun: {
    label: 'StepFun',
    cn: '阶跃星辰',
    icon: 'icon-stepfun',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://platform.stepfun.com/interface-key',
    defaultBaseUrl: 'https://api.stepfun.com/v1',
  },
  MiniMax: {
    label: 'MiniMax',
    cn: 'MiniMax',
    icon: 'icon-minimax',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://api.minimax.chat/user-center/basic-information/interface-key',
    defaultBaseUrl: 'https://api.minimax.chat/v1',
  },
  Groq: {
    label: 'Groq',
    cn: 'Groq',
    icon: 'icon-groq',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://console.groq.com/keys',
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
  },
  Together: {
    label: 'Together',
    cn: 'Together',
    icon: 'icon-together',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://api.together.xyz/settings/api-keys',
    defaultBaseUrl: 'https://api.together.xyz/v1',
  },
  Fireworks: {
    label: 'Fireworks',
    cn: 'Fireworks',
    icon: 'icon-fireworks',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://fireworks.ai/account/api-keys',
    defaultBaseUrl: 'https://api.fireworks.ai/inference/v1',
  },
  Mistral: {
    label: 'Mistral',
    cn: 'Mistral',
    icon: 'icon-mistral',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://console.mistral.ai/api-keys',
    defaultBaseUrl: 'https://api.mistral.ai/v1',
  },
  Perplexity: {
    label: 'Perplexity',
    cn: 'Perplexity',
    icon: 'icon-perplexity',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://www.perplexity.ai/settings/api',
    defaultBaseUrl: 'https://api.perplexity.ai',
  },
  Grok: {
    label: 'Grok',
    cn: 'Grok',
    icon: 'icon-grok',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://console.x.ai',
    defaultBaseUrl: 'https://api.x.ai/v1',
  },
  Hyperbolic: {
    label: 'Hyperbolic',
    cn: 'Hyperbolic',
    icon: 'icon-hyperbolic',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://app.hyperbolic.xyz/api-keys',
    defaultBaseUrl: 'https://api.hyperbolic.xyz/v1',
  },
  ModelScope: {
    label: 'ModelScope',
    cn: '魔搭社区',
    icon: 'icon-modelscope',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://modelscope.cn/my/myaccesstoken',
    defaultBaseUrl: 'https://api-inference.modelscope.cn/v1',
  },
  Other: {
    label: 'Other',
    cn: '其他',
    icon: 'icon-a-AIshezhi',
    urlWrite: true,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: '',
    defaultBaseUrl: '',
  },
};
