// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Model is the predicate function for model builders.
type Model func(*sql.Selector)

// ModelProvider is the predicate function for modelprovider builders.
type ModelProvider func(*sql.Selector)

// ModelProviderModel is the predicate function for modelprovidermodel builders.
type ModelProviderModel func(*sql.Selector)
