// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Model is the predicate function for model builders.
type Model func(*sql.Selector)

// ModelAPIConfig is the predicate function for modelapiconfig builders.
type ModelAPIConfig func(*sql.Selector)
